apiVersion: apps/v1
kind: Deployment
metadata:
  name: sortdrivers-deployment
  namespace: prpo-microservices
  labels:
    app: sortdrivers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sortdrivers
  template:
    metadata:
      labels:
        app: sortdrivers
    spec:
      containers:
      - name: sortdrivers
        image: prporegistry.azurecr.io/sortdrivers:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: sortdrivers-service
  namespace: prpo-microservices
spec:
  type: ClusterIP
  selector:
    app: sortdrivers
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
